name: PHPUnit

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false

      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP, Composer and Extensions
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, fileinfo, mbstring, sqlite3

      - name: Install dependencies
        run: composer install --optimize-autoloader --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Run tests
        run: php vendor/bin/phpunit
